### ISSUE TITLE
bug with tgag

### ISSUE THREAD

**Issue by ghost** [RussEfarmer/Persistent-Gags-and-Mutes#1]
I am using tgag and tmute on my TTT server and the following bug is happening: after a player's tgag is finished and he gets the automatic untgag, the player still can't talk, this is fixed if the player disconnects and reconnects to the server.

Also, I suggest adding a notification to let the player know that they can't talk yet because they are tgag and/or tmute. The [pgag](https://github.com/kralicky/Custom-ULX-Commands/blob/master/CustomCommands/lua/ulx/modules/sh/cc_pgag.lua#L83) and [pmute](https://github.com/kralicky/Custom-ULX-Commands/blob/master/CustomCommands/lua/ulx/modules/sh/cc_pmute.lua#L76) have this notification and it is weird here not to have it.

**Comment by RussEfarmer** [comment]
I'll check it out, sorry for getting to this late, I don't do Garry's Mod stuff that often. In the meantime I would try disabling some addons one at a time to see if anything else is causing it to break
